spring.application.name=distributed-task-engine

# PostgreSQL Configuration (Neon)
spring.datasource.url=jdbc:postgresql://ep-patient-scene-ax8auoe2-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Kw2ULZIV3cJR
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Upstash Redis Configuration
spring.data.redis.host=sensible-vervet-131641.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAgI5AAIgcDEwMWM5NjJiOTYwMjQ0OWFmYTI3ZjMyOTk0MTQyYzkzMQ
spring.data.redis.ssl.enabled=true
